import type { Property, Service, Testimonial, BlogPost, Client } from './types';
import { HomeIcon, BuildingOffice2Icon, BanknotesIcon, UserGroupIcon, ShieldCheckIcon, ChatBubbleBottomCenterTextIcon } from '@heroicons/react/24/outline';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Luxury Villa with Ocean View',
    price: 2500000,
    location: 'Malibu, California',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    type: 'Villa',
    status: 'For Sale',
    images: [
      'https://picsum.photos/seed/prop1_1/800/600',
      'https://picsum.photos/seed/prop1_2/800/600',
      'https://picsum.photos/seed/prop1_3/800/600',
      'https://picsum.photos/seed/prop1_4/800/600',
    ],
    description: 'Breathtaking oceanfront villa with panoramic views, an infinity pool, and state-of-the-art amenities. Experience coastal living at its finest in this architectural masterpiece.',
    features: ['Infinity Pool', 'Home Theater', 'Gourmet Kitchen', '3-Car Garage', 'Smart Home System'],
    amenities: ['Private Beach Access', '24/7 Security', 'Fitness Center', 'Spa & Sauna'],
    agent: { name: 'John Doe', imageUrl: 'https://picsum.photos/seed/agent1/200/200', phone: '123-456-7890', email: 'john.doe@prestige.com' },
    yearBuilt: 2022,
  },
  {
    id: '2',
    title: 'Modern Downtown Loft',
    price: 850000,
    location: 'New York, New York',
    bedrooms: 2,
    bathrooms: 2,
    area: 1800,
    type: 'Apartment',
    status: 'Sold',
    images: [
      'https://picsum.photos/seed/prop2_1/800/600',
      'https://picsum.photos/seed/prop2_2/800/600',
      'https://picsum.photos/seed/prop2_3/800/600',
    ],
    description: 'Chic and spacious loft in the heart of the city. Featuring high ceilings, exposed brick, and large windows with stunning city views. Perfect for urban professionals.',
    features: ['High Ceilings', 'Exposed Brick', 'Hardwood Floors', 'Modern Appliances'],
    amenities: ['Rooftop Terrace', 'Concierge Service', 'Gym', 'Pet Friendly'],
    agent: { name: 'Jane Smith', imageUrl: 'https://picsum.photos/seed/agent2/200/200', phone: '098-765-4321', email: 'jane.s@prestige.com' },
    yearBuilt: 2018,
  },
  {
    id: '3',
    title: 'Cozy Suburban Family Home',
    price: 650000,
    location: 'Austin, Texas',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    type: 'House',
    status: 'For Sale',
    images: [
      'https://picsum.photos/seed/prop3_1/800/600',
      'https://picsum.photos/seed/prop3_2/800/600',
      'https://picsum.photos/seed/prop3_3/800/600',
    ],
    description: 'Charming family home in a quiet, friendly neighborhood. This property boasts a large backyard with a pool, a newly renovated kitchen, and is located in a top-rated school district.',
    features: ['Large Backyard', 'Swimming Pool', 'Renovated Kitchen', 'Fireplace'],
    amenities: ['Community Park', 'Top School District', 'Close to Shopping'],
    agent: { name: 'John Doe', imageUrl: 'https://picsum.photos/seed/agent1/200/200', phone: '123-456-7890', email: 'john.doe@prestige.com' },
    yearBuilt: 2015,
  },
   {
    id: '4',
    title: 'Riverside Condominium',
    price: 1200000,
    location: 'Chicago, Illinois',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    type: 'Condo',
    status: 'For Rent',
    images: [
      'https://picsum.photos/seed/prop4_1/800/600',
      'https://picsum.photos/seed/prop4_2/800/600',
    ],
    description: 'Stunning condo with breathtaking views of the Chicago River and city skyline. Floor-to-ceiling windows, a private balcony, and access to premium building amenities.',
    features: ['Private Balcony', 'Floor-to-ceiling windows', 'Walk-in Closets', 'Chef\'s Kitchen'],
    amenities: ['Indoor Pool', 'Valet Parking', 'Business Center', 'Social Lounge'],
    agent: { name: 'Emily White', imageUrl: 'https://picsum.photos/seed/agent3/200/200', phone: '555-123-4567', email: 'emily.w@prestige.com' },
    yearBuilt: 2020,
  },
  {
    id: '5',
    title: 'Mountain Retreat Cabin',
    price: 950000,
    location: 'Aspen, Colorado',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    type: 'House',
    status: 'Paused',
    images: [
      'https://picsum.photos/seed/prop5_1/800/600',
      'https://picsum.photos/seed/prop5_2/800/600',
      'https://picsum.photos/seed/prop5_3/800/600',
    ],
    description: 'A beautiful log cabin style home nestled in the mountains. Features rustic charm with modern luxuries, including a hot tub, large stone fireplace, and panoramic mountain views.',
    features: ['Hot Tub', 'Stone Fireplace', 'Large Deck', 'Ski-in/Ski-out potential'],
    amenities: ['Private Woods', 'Hiking Trails Access', 'Gated Community'],
    agent: { name: 'Jane Smith', imageUrl: 'https://picsum.photos/seed/agent2/200/200', phone: '098-765-4321', email: 'jane.s@prestige.com' },
    yearBuilt: 2010,
  },
  {
    id: '6',
    title: 'Historic Brownstone',
    price: 3200000,
    location: 'Brooklyn, New York',
    bedrooms: 6,
    bathrooms: 5,
    area: 4800,
    type: 'House',
    status: 'For Sale',
    images: [
      'https://picsum.photos/seed/prop6_1/800/600',
      'https://picsum.photos/seed/prop6_2/800/600',
    ],
    description: 'Magnificently restored historic brownstone in a prime Brooklyn neighborhood. Original details have been preserved alongside modern updates for a perfect blend of old and new.',
    features: ['Original Woodwork', 'Garden Level Apartment', 'Rooftop Deck', 'Wine Cellar'],
    amenities: ['Tree-lined Street', 'Close to Subway', 'Famous Restaurants Nearby'],
    agent: { name: 'John Doe', imageUrl: 'https://picsum.photos/seed/agent1/200/200', phone: '123-456-7890', email: 'john.doe@prestige.com' },
    yearBuilt: 1910,
  },
];

export const SERVICES: Service[] = [
  {
    icon: HomeIcon,
    title: 'Property Sales',
    description: 'We provide expert assistance for selling your property at the best market price, handling everything from listing to closing.',
  },
  {
    icon: BuildingOffice2Icon,
    title: 'Property Buying',
    description: 'Our team helps you find and purchase your dream home, guiding you through every step of the buying process with personalized service.',
  },
  {
    icon: BanknotesIcon,
    title: 'Mortgage Assistance',
    description: 'We connect you with trusted financial partners to secure the best mortgage rates and terms for your new property.',
  },
  {
    icon: UserGroupIcon,
    title: 'Property Management',
    description: 'Comprehensive management services for your rental properties, ensuring peace of mind and maximizing your investment return.',
  },
  {
    icon: ShieldCheckIcon,
    title: 'Legal Consulting',
    description: 'Access to our network of real estate legal experts to ensure all transactions are smooth, secure, and legally sound.',
  },
  {
    icon: ChatBubbleBottomCenterTextIcon,
    title: 'Market Analysis',
    description: 'Receive in-depth market analysis and property valuation to make informed decisions whether you are buying or selling.',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: 'Working with Prestige Realty was a dream. They were professional, knowledgeable, and made the entire process of buying our first home seamless and stress-free. Highly recommended!',
    author: 'The Johnson Family',
    location: 'Austin, TX',
  },
  {
    quote: 'They sold our house in less than a week for above asking price! The marketing was top-notch and their negotiation skills are unparalleled. We couldn\'t be happier.',
    author: 'Maria Garcia',
    location: 'Malibu, CA',
  },
  {
    quote: 'As an investor, I rely on expert advice. The team at Prestige Realty understands the market inside and out. They have been instrumental in growing my property portfolio.',
    author: 'David Chen',
    location: 'New York, NY',
  },
];

export const BLOG_POSTS: BlogPost[] = [
    {
        id: '1',
        title: '5 Tips for First-Time Homebuyers in 2024',
        author: 'Jane Smith',
        date: 'July 15, 2024',
        excerpt: 'Navigating the real estate market for the first time can be daunting. Here are five essential tips to help you make a smart and confident purchase...',
        imageUrl: 'https://picsum.photos/seed/blog1/600/400',
        category: 'Buying',
    },
    {
        id: '2',
        title: 'How to Stage Your Home to Sell for Top Dollar',
        author: 'John Doe',
        date: 'July 10, 2024',
        excerpt: 'Home staging is a critical step in the selling process. Learn how to showcase your home\'s best features to attract buyers and maximize your profit.',
        imageUrl: 'https://picsum.photos/seed/blog2/600/400',
        category: 'Selling',
    },
    {
        id: '3',
        title: 'Understanding the Current Mortgage Rate Trends',
        author: 'Emily White',
        date: 'July 5, 2024',
        excerpt: 'Mortgage rates are always changing. We break down the current trends and what they mean for you whether you\'re buying, selling, or refinancing.',
        imageUrl: 'https://picsum.photos/seed/blog3/600/400',
        category: 'Finance',
    },
];

export const MOCK_CLIENTS: Client[] = [
    { id: 'c1', name: 'Alice Johnson', email: 'alice.j@example.com', phone: '555-0101', status: 'New', inquiryDate: '2024-07-20' },
    { id: 'c2', name: 'Bob Williams', email: 'bob.w@example.com', phone: '555-0102', status: 'Contacted', inquiryDate: '2024-07-19' },
    { id: 'c3', name: 'Charlie Brown', email: 'charlie.b@example.com', phone: '555-0103', status: 'Appointment Scheduled', inquiryDate: '2024-07-18' },
    { id: 'c4', name: 'Diana Miller', email: 'diana.m@example.com', phone: '555-0104', status: 'Closed', inquiryDate: '2024-06-15' },
    { id: 'c5', name: 'Ethan Davis', email: 'ethan.d@example.com', phone: '555-0105', status: 'Lost', inquiryDate: '2024-07-17' },
    { id: 'c6', name: 'Fiona Garcia', email: 'fiona.g@example.com', phone: '555-0106', status: 'New', inquiryDate: '2024-07-21' },
];